//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorAppo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Logi
    {
        [Required]
        public int UserID { get; set; }
        [Required]
        public string Pwd { get; set; }
        [Required]
        public string UserRole { get; set; }
    }
    //public enum Role
    //{
    //    admin,
    //    receptionist,
    //    doctor
    //}
}
