//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorAppo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tblPatientDetail
    {
        
        public int iId { get; set; }
        [Required]
        public string cName { get; set; }
        [Required]
        public string cUserName { get; set; }
        [Required]
        public string vPassword { get; set; }
        [Required]
        public string vAddress { get; set; }
        [Required]
        public Nullable<System.DateTime> dDateOfBirth { get; set; }
        [Required]
        public string cGender { get; set; }
        [Required]
        [EmailAddress]
        public string vEmail { get; set; }
        [Required]
        [RegularExpression("^([07][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9] | 8[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9] | 9[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9])$", ErrorMessage = "Enter Valid Mobile Number")]
        public long iPhone { get; set; }
        [Required]
        public string Security_Question { get; set; }
        [Required]
        public string Answer { get; set; }
    }
}
